name = "WaterWaves"
uuid = "0f39c4df-e15c-4617-a3a4-ab9467413018"
authors = ["Theodoros Gerostathis"]
version = "0.0.3"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
